model:
  d_model: 512
  num_layers: 4
  d_ff: 1344
  theta: 10000
  num_heads: 16
  max_seq_len: 256    # RoPE位置编码预计算cos sin表
  vocab_size: 10000
  use_rmsnorm: false

training:
  batch_size: 32
  train_context_length: 256
  max_iters: 10000

  max_lr: 0.0003
  min_lr: 0.00003
  warmup_iters: 500
  cosine_cycle_iters: 10000

  betas: [0.9, 0.95]
  eps: 1.0e-8
  weight_decay: 0.01
  max_l2_norm: 1.0


experiment:
  seed: 42

runtime:
  device: cuda:5

data:
  train_path: artifacts/datasets/tinystories_full_10k.npy
  val_path: artifacts/datasets/tinystories_full_10k_valid.npy

checkpoint:
  output_dir: checkpoints/tinystories_no_rmsnorm_lr_3e4_v2
  save_interval: 1000
  resume_from: null

  log_interval: 10
  eval_interval: 200
  eval_batches: 10
